title: Neli Tankova # your name (or website title) here
logo: "/images/Photo_NT_5.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with interests in analytics, strategy and sales and a master's degree studies in Big Data Analytics from Sofia University St. Kliment Ohridski. Previously at Alpha Solar Ltd. (project development and project management), EFG Eurobank (senior auditor/fraud investigator).
  <br><br>
  Second description 
  <br><br>
  <a href="https://bg.linkedin.com/in/nelly-tankova-12815037">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
